Improve enforce-data-keys-javadoc-for-actions script, inline illegal imports checks (message format, (non)null(able))

diff --git a/scripts/enforce-data-keys-javadoc-for-actions b/scripts/enforce-data-keys-javadoc-for-actions
--- a/scripts/enforce-data-keys-javadoc-for-actions
+++ b/scripts/enforce-data-keys-javadoc-for-actions
@@ -1,5 +1,7 @@
 #!/usr/bin/env bash
 
+set -e -o pipefail -u
+
 self_dir=$(cd "$(dirname "$0")" &>/dev/null; pwd -P)
 source "$self_dir"/utils.sh
 
@@ -8,5 +10,5 @@ if git grep --files-without-match '^ \* Expects DataKeys:$' -- '*Action.java'; t
 fi
 
 if git grep --files-with-match 'getProject' -- '*Action.java' | xargs git grep --files-without-match '^ \*  <li>{@link CommonDataKeys#PROJECT}</li>$'; then
-  die '\nProvide a Javadoc documenting the `DataKey`s required by `com.intellij.openapi.actionSystem.AnActionEvent.getProject` in the above files.'
+  die '\nProvide a Javadoc documenting the `DataKey` (`CommonDataKeys#PROJECT`) required by the method `com.intellij.openapi.actionSystem.AnActionEvent#getProject` invoked in the above files.'
 fi
