Harden scripts/run-ui-tests against race conditions

diff --git a/scripts/run-ui-tests b/scripts/run-ui-tests
--- a/scripts/run-ui-tests
+++ b/scripts/run-ui-tests
@@ -5,6 +5,15 @@ set -e -o pipefail -u
 self_dir=$(cd "$(dirname "$0")" &>/dev/null; pwd -P)
 source "$self_dir"/utils.sh
 
+robot_server_port=8080
+function is_robot_server_listening() {
+  nc -z localhost $robot_server_port
+}
+
+if is_robot_server_listening; then
+  jps -mlv
+  die "A process is listening on port $robot_server_port (possibly an old instance of IDE for UI tests is still running? see the output of 'jps -mlv' above); aborting"
+fi
 
 intellij_version=${1-} # can be skipped; the same IntelliJ version that the plugin has been built against will be assumed
 
@@ -22,26 +31,44 @@ function ide_logs_from_this_run() {
 # but unfortunately xvfb-run available for Debian Buster (base of our CI image) doesn't support the latter.
 command=${CI:+xvfb-run --auto-servernum}
 gradle_run_ide_log=~/gradlew-runIdeForUiTests.log
-$command ./gradlew -PintellijVersionForRunIde=$intellij_version --max-workers=1 -Dorg.gradle.jvmargs=-Xmx256M runIdeForUiTests >$gradle_run_ide_log 2>&1 &
+$command ./gradlew -PintellijVersionForRunIde=$intellij_version --no-daemon --max-workers=1 -Dorg.gradle.jvmargs=-Xmx256M runIdeForUiTests >$gradle_run_ide_log 2>&1 &
 
-# $! expands to the PID of the last process executed in the background
-ide_pid=$!
-function is_ide_running() {
-  ps -p $ide_pid >/dev/null 2>&1
+# $! expands to the PID of the last process executed in the background.
+wrapper_process_pid=$!
+function is_wrapper_process_running() {
+  ps -p $wrapper_process_pid >/dev/null 2>&1
 }
 
-# Let's make sure the IDE process is terminated in case gracefully closing the IDE in @After failed for whatever reason.
 function finish() {
-  if is_ide_running; then
-    kill -TERM $ide_pid || true  # ignoring exit code in case the process just terminated between `is_ide_running` and `kill`
+  if is_wrapper_process_running; then
+    echo 'Sending TERM to the wrapper process...'
+    # Ignoring exit code in case the process just terminated between `is_wrapper_process_running` and `kill`.
+    kill -TERM $wrapper_process_pid || true
   fi
-  # Let's wait until IDE process is terminated to avoid any risk of race conditions
+  # Let's wait until the wrapper process is terminated to avoid any risk of race conditions
   # when another UI test is to be run right after this script completes.
   local count=0
-  while is_ide_running; do
-    # Rather unlikely, IDE process tends to shut down quickly on receiving SIGTERM.
-    if [[ $((count++)) -eq 10 ]]; then
-      kill -KILL $ide_pid || true
+  while is_wrapper_process_running; do
+    if (( count++ == 10 )); then
+      # Rather unlikely, wrapper process tends to shut down quickly on receiving SIGTERM.
+      echo 'Sending KILL to the wrapper process...'
+      kill -KILL $wrapper_process_pid || true
+    fi
+    echo 'Waiting for the wrapper process to shut down...'
+    sleep 1.0
+  done
+
+  # If the IDE process still occupies the port at this point, let's kill the IDE process itself.
+  if is_robot_server_listening; then
+    echo 'Sending TERM to IDE process...'
+    fuser --kill -TERM $robot_server_port/tcp >/dev/null 2>&1 || true
+  fi
+  count=0
+  while is_robot_server_listening; do
+    if (( count++ == 10 )); then
+      # Rather unlikely, IDE tends to shut down quickly on receiving SIGTERM.
+      echo 'Sending KILL to IDE process...'
+      fuser --kill -KILL $robot_server_port/tcp >/dev/null 2>&1 || true
     fi
     echo 'Waiting for IDE process to shut down...'
     sleep 1.0
@@ -52,12 +79,12 @@ trap finish EXIT
 gradle_run_ide_log_last_line=0
 # Let's wait until Remote Robot plugin living within the IDE starts listening.
 info 'Logs of gradle runIdeForUiTests'
-while ! nc -z localhost 8080; do
+until is_robot_server_listening; do
   sleep 0.5
   tail -n+$((gradle_run_ide_log_last_line+1)) $gradle_run_ide_log
   gradle_run_ide_log_last_line=$(wc -l < $gradle_run_ide_log)
-  if ! is_ide_running; then
-    die 'IDE failed to start, aborting'
+  if ! is_wrapper_process_running; then
+    die 'Wrapper process has been terminated before Remote Robot plugin started listening; aborting'
   fi
 done
 
