Fix execution of UI tests across multiple IDE versions

diff --git a/scripts/run-ui-tests b/scripts/run-ui-tests
--- a/scripts/run-ui-tests
+++ b/scripts/run-ui-tests
@@ -17,21 +17,21 @@ fi
 
 intellij_version=${1-} # can be skipped; the same IntelliJ version that the plugin has been built against will be assumed
 
-ide_log=build/idea-sandbox/system/log/idea.log
-# idea.log is not automatically cleared before each `runIde(forUiTests)`
-# and we don't want to print the potential logs from the previous runs.
-ide_log_last_line=$(cat $ide_log 2>/dev/null | wc -l || true)  # will be 0 if $ide_log doesn't exist yet
-
-function ide_logs_from_this_run() {
-  tail -n+$((ide_log_last_line+1)) $ide_log
-}
+# We need to clean up the sandbox in case it has originally been set up for a different version of IDE;
+# the configs are not forward-compatible between the releases (e.g. 2020.1 crashes on 2020.2 configs).
+rm -rf build/idea-sandbox/
 
 # If we're on CI, run IDE on X Virtual Framebuffer; otherwise, open a regular window.
 # --auto-servernum is deprecated in favor of --auto-display,
 # but unfortunately xvfb-run available for Debian Buster (base of our CI image) doesn't support the latter.
 command=${CI:+xvfb-run --auto-servernum}
 gradle_run_ide_log=~/gradlew-runIdeForUiTests.log
-$command ./gradlew -PintellijVersionForRunIde=$intellij_version --no-daemon --max-workers=1 -Dorg.gradle.jvmargs=-Xmx256M runIdeForUiTests >$gradle_run_ide_log 2>&1 &
+$command ./gradlew \
+  -PintellijVersionForRunIde=$intellij_version \
+  --no-daemon \
+  --max-workers=1 \
+  -Dorg.gradle.jvmargs=-Xmx256M \
+  runIdeForUiTests >$gradle_run_ide_log 2>&1 &
 
 # $! expands to the PID of the last process executed in the background.
 wrapper_process_pid=$!
@@ -88,11 +88,24 @@ until is_robot_server_listening; do
   fi
 done
 
+ide_log=build/idea-sandbox/system/log/idea.log
+ide_log_last_line=0
+
+function ide_logs_from_this_run() {
+  tail -n+$((ide_log_last_line+1)) $ide_log
+}
+
 info 'Logs of gradle uiTests:test'
-./gradlew -PenableUiTests --info --max-workers=1 -Dorg.gradle.jvmargs=-Xmx256M uiTests:test || {
-  info 'Logs of IDE under test'
-  ide_logs_from_this_run
-  die 'UI tests failed; inspect Gradle and IDE logs above'
+./gradlew \
+  -PenableUiTests \
+  -PtestResultsSubdir="$intellij_version" \
+  --info \
+  --max-workers=1 \
+  -Dorg.gradle.jvmargs=-Xmx256M \
+  uiTests:test || {
+    info 'Logs of IDE under test'
+    ide_logs_from_this_run
+    die 'UI tests failed; inspect Gradle and IDE logs above'
 }
 
 if ide_logs_from_this_run | grep -q ' ERROR - '; then
