Smooth out the verify artifact contents script

diff --git a/scripts/verify-artifact-contents b/scripts/verify-artifact-contents
--- a/scripts/verify-artifact-contents
+++ b/scripts/verify-artifact-contents
@@ -17,24 +17,28 @@ function fail() {
 
 jars_in_plugin_zip=$(zipinfo -1 "$plugin_zip" | grep -Po '(?<=git-machete-intellij-plugin/lib/).*\.jar' | sort)
 
-gradle_subprojects=$(cat settings.gradle | grep -Po "(?<=include ').*(?=')" | sort)
-for project in "git-machete-intellij-plugin" $gradle_subprojects; do
+gradle_projects=$(cat settings.gradle | grep -Po "(?<=').*(?=')" | sort)
+for project in $gradle_projects; do
   expected_jar="$project-$plugin_version.jar"
   grep -qxF "$expected_jar" <<< "$jars_in_plugin_zip" || fail "$expected_jar is expected but missing from $plugin_zip"
 done
 
-expected_libraries="org\.eclipse\.jgit reflections slf4j-lambda-core vavr vavr-match"
-for lib in $expected_libraries; do
-  grep -qx "$lib-.*\.jar" <<< "$jars_in_plugin_zip" || fail "$lib jar is expected but missing from $plugin_zip"
+expected_libraries=(org.eclipse.jgit reflections slf4j-lambda-core vavr vavr-match)
+for lib in ${expected_libraries[@]}; do
+  grep -qEx "${lib//./\\.}-[0-9.]+.*\.jar" <<< "$jars_in_plugin_zip" || fail "$lib jar is expected but missing from $plugin_zip"
 done
 
 # We don't want either slf4j-api or any SLF4J implementation jars in the final plugin artifact
 # since this would lead to a linker error (for api) or an SLF4J error (for impl) in the runtime.
-forbidden_library_prefixes="checker lombok slf4j-api slf4j-simple"
-for lib in $forbidden_library_prefixes; do
+forbidden_library_prefixes=(checker lombok slf4j)
+for lib in ${forbidden_library_prefixes[@]}; do
   if matching_jars=$(grep "^$lib" <<< "$jars_in_plugin_zip"); then
     for jar in $matching_jars; do
-      fail "$jar is forbidden but present in $plugin_zip"
+      jar_base_name=${jar/-[0-9]*/}
+      # Maybe the library matches the forbidden prefix but is still expected (e.g. slf4j-lambda-core)?
+      if ! [[ " ${expected_libraries[@]} " == *\ $jar_base_name\ * ]]; then
+        fail "$jar is forbidden but present in $plugin_zip"
+      fi
     done
   fi
 done
